{
 "title": "Projects",
 "description": "All project's  stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "vhost", "label": "vhost", "query": "label_values(virtual_host)" }
  ]
 },
 "panels": [
  {
   "title": "Error status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (status) (count_over_time({virtual_host=\"$vhost\",status=~\"(5.+)|(4.+)\"}[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "content": " <h1 style=\"text-align:center\">$vhost</h1>\n\n\n"
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({virtual_host=\"$vhost\"}[1m]))",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(promtail_custom_http_nginx_response_time_bucket{virtual_host=\"$vhost\"}[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(promtail_custom_http_nginx_response_time_bucket{virtual_host=\"$vhost\"}[5m])) by (le))",
     "legendFormat": "75 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(promtail_custom_http_nginx_response_time_bucket{virtual_host=\"$vhost\"}[5m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(promtail_custom_http_nginx_response_time_bucket{virtual_host=\"$vhost\"}[5m])) by (le))",
     "legendFormat": "25 percentile"
    }
   ]
  },
  {
   "title": "Bytes out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_http_nginx_response_bytes_sum{virtual_host=\"$vhost\"}[10m]))",
     "legendFormat": "bytes total"
    },
    {
     "expr": "sum(increase(promtail_custom_http_nginx_response_bytes_sum[10m])) by (request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Top slow request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(4, sum(increase(promtail_custom_http_nginx_response_time_sum{virtual_host=\"$vhost\",request!=\"\"}[10m]) / increase(promtail_custom_http_nginx_response_time_count{virtual_host=\"$vhost\",request!=\"\"}[10m])) by (request))",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}